import localFont from "next/font/local";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { ChatProvider } from "@/context/ChatContext";
import { Toaster } from "../components/ui/toaster";
import { auth } from "@/auth";

const geistSans = localFont({
  src: "../../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Bubble, Virtual Assistant",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <ChatProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
            <Toaster />
          </body>
        </ChatProvider>
      </html>
    </SessionProvider>
  );
}
